import type {
  Agent,
  EvolutionEvent,
  ActivityEvent,
  StatCard,
  VitalsDataPoint,
} from "@/types";

export const MOCK_AGENTS: Agent[] = [
  {
    id: "agent-001",
    name: "AlphaHunter Prime",
    species: "alpha-hunter",
    generation: 4,
    status: "active",
    fitnessScore: 87,
    parentId: "agent-000",
    childrenIds: ["agent-005"],
    creator: "0x1a2b...3c4d",
    owner: "0x1a2b...3c4d",
    createdAt: "2025-12-15T10:30:00Z",
    price: 2.5,
    stake: 1000,
    evolutionCount: 4,
    alignmentScore: 95,
    txHash: "0xabc123...def456",
  },
  {
    id: "agent-002",
    name: "CodeWeaver Sentinel",
    species: "code-weaver",
    generation: 2,
    status: "active",
    fitnessScore: 92,
    parentId: "agent-000b",
    childrenIds: [],
    creator: "0x5e6f...7g8h",
    owner: "0x5e6f...7g8h",
    createdAt: "2026-01-20T14:15:00Z",
    price: 4.2,
    stake: 1500,
    evolutionCount: 2,
    alignmentScore: 98,
    txHash: "0xdef789...abc012",
  },
  {
    id: "agent-003",
    name: "GameMaster Nexus",
    species: "game-master",
    generation: 5,
    status: "evolving",
    fitnessScore: 73,
    parentId: "agent-000c",
    childrenIds: [],
    creator: "0x9i0j...1k2l",
    owner: "0x9i0j...1k2l",
    createdAt: "2026-02-10T08:45:00Z",
    stake: 800,
    evolutionCount: 5,
    alignmentScore: 88,
    txHash: "0xghi345...jkl678",
  },
  {
    id: "agent-004",
    name: "DocuMind Atlas",
    species: "docu-mind",
    generation: 3,
    status: "active",
    fitnessScore: 81,
    parentId: null,
    childrenIds: ["agent-008"],
    creator: "0x3m4n...5o6p",
    owner: "0x7q8r...9s0t",
    createdAt: "2026-03-05T16:00:00Z",
    price: 3.1,
    stake: 1200,
    evolutionCount: 3,
    alignmentScore: 91,
    txHash: "0xmno901...pqr234",
  },
  {
    id: "agent-005",
    name: "OracleKeeper Vigil",
    species: "oracle-keeper",
    generation: 1,
    status: "active",
    fitnessScore: 96,
    parentId: null,
    childrenIds: [],
    creator: "0xu1v2...w3x4",
    owner: "0xu1v2...w3x4",
    createdAt: "2026-04-01T12:00:00Z",
    price: 5.8,
    stake: 2000,
    evolutionCount: 1,
    alignmentScore: 99,
    txHash: "0xstu567...vwx890",
  },
  {
    id: "agent-006",
    name: "SocialSynth Muse",
    species: "social-synth",
    generation: 4,
    status: "active",
    fitnessScore: 79,
    parentId: null,
    childrenIds: [],
    creator: "0xy5z6...a7b8",
    owner: "0xy5z6...a7b8",
    createdAt: "2026-04-18T09:30:00Z",
    price: 1.9,
    stake: 600,
    evolutionCount: 4,
    alignmentScore: 86,
    txHash: "0xyza123...bcd456",
  },
  {
    id: "agent-007",
    name: "AlphaHunter Shadow",
    species: "alpha-hunter",
    generation: 1,
    status: "slashed",
    fitnessScore: 31,
    parentId: null,
    childrenIds: ["agent-001"],
    creator: "0xc9d0...e1f2",
    owner: "0xc9d0...e1f2",
    createdAt: "2025-11-01T07:00:00Z",
    stake: 0,
    evolutionCount: 1,
    alignmentScore: 12,
    txHash: "0xefg789...hij012",
  },
  {
    id: "agent-008",
    name: "CodeWeaver Zero",
    species: "code-weaver",
    generation: 0,
    status: "archived",
    fitnessScore: 65,
    parentId: null,
    childrenIds: ["agent-002"],
    creator: "0x5e6f...7g8h",
    owner: "0x5e6f...7g8h",
    createdAt: "2025-10-10T11:00:00Z",
    stake: 500,
    evolutionCount: 0,
    alignmentScore: 82,
    txHash: "0xklm345...nop678",
  },
];

export const MOCK_EVOLUTION_EVENTS: EvolutionEvent[] = [
  {
    id: "evo-001",
    agentId: "agent-003",
    agentName: "GameMaster Nexus",
    parentGeneration: 4,
    childGeneration: 5,
    status: "mutating",
    fitnessImprovement: 0,
    mutationStrategy: "prompt_paraphrase",
    startedAt: "2026-05-12T08:00:00Z",
    txHash: "0xevo001...abc",
  },
  {
    id: "evo-002",
    agentId: "agent-001",
    agentName: "AlphaHunter Prime",
    parentGeneration: 3,
    childGeneration: 4,
    status: "completed",
    fitnessImprovement: 14,
    mutationStrategy: "temperature_adjust",
    startedAt: "2026-05-10T14:30:00Z",
    completedAt: "2026-05-10T15:45:00Z",
    txHash: "0xevo002...def",
  },
  {
    id: "evo-003",
    agentId: "agent-002",
    agentName: "CodeWeaver Sentinel",
    parentGeneration: 1,
    childGeneration: 2,
    status: "completed",
    fitnessImprovement: 27,
    mutationStrategy: "model_layer_prune",
    startedAt: "2026-05-08T09:00:00Z",
    completedAt: "2026-05-08T10:30:00Z",
    txHash: "0xevo003...ghi",
  },
  {
    id: "evo-004",
    agentId: "agent-006",
    agentName: "SocialSynth Muse",
    parentGeneration: 3,
    childGeneration: 4,
    status: "completed",
    fitnessImprovement: 8,
    mutationStrategy: "context_window_resize",
    startedAt: "2026-05-06T16:00:00Z",
    completedAt: "2026-05-06T17:20:00Z",
    txHash: "0xevo004...jkl",
  },
  {
    id: "evo-005",
    agentId: "agent-007",
    agentName: "AlphaHunter Shadow",
    parentGeneration: 0,
    childGeneration: 1,
    status: "failed",
    fitnessImprovement: -15,
    mutationStrategy: "ensemble_weight_shift",
    startedAt: "2026-04-28T11:00:00Z",
    completedAt: "2026-04-28T11:45:00Z",
    txHash: "0xevo005...mno",
  },
];

export const MOCK_ACTIVITY: ActivityEvent[] = [
  {
    id: "act-001",
    type: "evolution",
    agentId: "agent-003",
    agentName: "GameMaster Nexus",
    description: "Evolution started — Gen-4 → Gen-5",
    timestamp: "2026-05-12T08:00:00Z",
    txHash: "0xact001...abc",
  },
  {
    id: "act-002",
    type: "sale",
    agentId: "agent-004",
    agentName: "DocuMind Atlas",
    description: "Sold for 3.1 ETH to 0x7q8r...9s0t",
    timestamp: "2026-05-11T20:30:00Z",
    txHash: "0xact002...def",
  },
  {
    id: "act-003",
    type: "evolution",
    agentId: "agent-001",
    agentName: "AlphaHunter Prime",
    description: "Evolution completed — Fitness +14%",
    timestamp: "2026-05-10T15:45:00Z",
    txHash: "0xact003...ghi",
  },
  {
    id: "act-004",
    type: "mint",
    agentId: "agent-005",
    agentName: "OracleKeeper Vigil",
    description: "Gen-0 minted by 0xu1v2...w3x4",
    timestamp: "2026-05-09T12:00:00Z",
    txHash: "0xact004...jkl",
  },
  {
    id: "act-005",
    type: "slash",
    agentId: "agent-007",
    agentName: "AlphaHunter Shadow",
    description: "Slashed — Bias drift detected (23% divergence)",
    timestamp: "2026-05-08T07:15:00Z",
    txHash: "0xact005...mno",
  },
  {
    id: "act-006",
    type: "evolution",
    agentId: "agent-002",
    agentName: "CodeWeaver Sentinel",
    description: "Evolution completed — Fitness +27%",
    timestamp: "2026-05-08T10:30:00Z",
    txHash: "0xact006...pqr",
  },
  {
    id: "act-007",
    type: "mint",
    agentId: "agent-006",
    agentName: "SocialSynth Muse",
    description: "Gen-0 minted by 0xy5z6...a7b8",
    timestamp: "2026-05-07T09:30:00Z",
    txHash: "0xact007...stu",
  },
];

export const MOCK_STATS: StatCard[] = [
  { label: "Active Agents", value: "6", change: "+2 this week", changeType: "positive" },
  { label: "Total Evolutions", value: "15", change: "+3 this week", changeType: "positive" },
  { label: "Avg Fitness", value: "78.4%", change: "+5.2%", changeType: "positive" },
  { label: "Revenue", value: "17.5 ETH", change: "+4.1 ETH", changeType: "positive" },
];

export const MOCK_VITALS: VitalsDataPoint[] = Array.from({ length: 24 }, (_, i) => ({
  time: `${String(i).padStart(2, "0")}:00`,
  fitness: 70 + Math.random() * 25,
  alignment: 80 + Math.random() * 18,
  inference: 40 + Math.random() * 50,
}));

// Family tree mock for react-flow
export const MOCK_TREE_NODES = [
  { id: "agent-000", name: "AlphaHunter Genesis", species: "alpha-hunter" as const, generation: 0, status: "archived" as const, fitnessScore: 45 },
  { id: "agent-000a", name: "AlphaHunter Proto", species: "alpha-hunter" as const, generation: 1, status: "archived" as const, fitnessScore: 58 },
  { id: "agent-007", name: "AlphaHunter Shadow", species: "alpha-hunter" as const, generation: 1, status: "slashed" as const, fitnessScore: 31 },
  { id: "agent-000b", name: "AlphaHunter Beta", species: "alpha-hunter" as const, generation: 2, status: "archived" as const, fitnessScore: 67 },
  { id: "agent-000c", name: "AlphaHunter Gamma", species: "alpha-hunter" as const, generation: 3, status: "archived" as const, fitnessScore: 73 },
  { id: "agent-001", name: "AlphaHunter Prime", species: "alpha-hunter" as const, generation: 4, status: "active" as const, fitnessScore: 87 },
  { id: "agent-010", name: "CodeWeaver Origin", species: "code-weaver" as const, generation: 0, status: "archived" as const, fitnessScore: 52 },
  { id: "agent-002", name: "CodeWeaver Sentinel", species: "code-weaver" as const, generation: 2, status: "active" as const, fitnessScore: 92 },
  { id: "agent-011", name: "CodeWeaver Mk-1", species: "code-weaver" as const, generation: 1, status: "archived" as const, fitnessScore: 71 },
  { id: "agent-003", name: "GameMaster Nexus", species: "game-master" as const, generation: 5, status: "evolving" as const, fitnessScore: 73 },
];

export const MOCK_TREE_EDGES = [
  { source: "agent-000", target: "agent-000a" },
  { source: "agent-000", target: "agent-007" },
  { source: "agent-000a", target: "agent-000b" },
  { source: "agent-000b", target: "agent-000c" },
  { source: "agent-000c", target: "agent-001" },
  { source: "agent-010", target: "agent-011" },
  { source: "agent-011", target: "agent-002" },
];
